# This file is a template, and might need editing before it works on your project.
# Read more about this script on this blog post https://about.gitlab.com/2018/10/24/setting-up-gitlab-ci-for-android-projects/, by Jason Lenny
# If you are interested in using Android with FastLane for publishing take a look at the Android-Fastlane template.

image: jangrewe/gitlab-ci-android

before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - chmod +x ./gradlew

cache:
     key: ${CI_PROJECT_ID}
     paths:
         - .gradle/

stages:
    - build

buildApp:
    stage: build
    script:
        - echo "sdk.dir=${ANDROID_HOME}" > local.properties
        - ./gradlew --no-daemon build
    artifacts:
        paths:
            - TeamCode/build/outputs/apk/release/TeamCode-release-unsigned.apk
            - TeamCode/build/outputs/apk/debug/TeamCode-debug.apk